name: CI

on:
  push:
  pull_request:

jobs:
  tooling:
    name: C++20 and Bash (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Verify
        run: make verify
